version: "2"
services:
  web:
    image: centos:7
    ports:
      - "5000:5001"
    command: ['/usr/bin/dumb-init', 'python', '/flaskapp/app.py']
    dev_overrides:
        volumes:
          - ../showdownapi/:/flaskapp
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    ports:
      - "9200:9200"
    command: ['elasticsearch']
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    ports:
      - 5601:5601
    environment:
      - "SERVER_NAME=localhost"
      - "ELASTICSEARCH_URL=http://elastic:9200"
      - "XPACK_SECURITY_ENABLED=false"
    links:
      - elastic:elastic
registries: {}
